BEGIN TRANSACTION;

-- Drop foreign key constraints only if the table exists
IF OBJECT_ID('Operator', 'U') IS NOT NULL
    ALTER TABLE Operator DROP CONSTRAINT IF EXISTS FK_Operator_OperatorType;

IF OBJECT_ID('Route', 'U') IS NOT NULL
    ALTER TABLE Route DROP CONSTRAINT IF EXISTS FK_Route_Operator;
IF OBJECT_ID('Route', 'U') IS NOT NULL
    ALTER TABLE Route DROP CONSTRAINT IF EXISTS FK_Route_Town_From;
IF OBJECT_ID('Route', 'U') IS NOT NULL
    ALTER TABLE Route DROP CONSTRAINT IF EXISTS FK_Route_Town_To;
IF OBJECT_ID('Route', 'U') IS NOT NULL
    ALTER TABLE Route DROP CONSTRAINT IF EXISTS FK_Route_User_CreatedBy;
IF OBJECT_ID('Route', 'U') IS NOT NULL
    ALTER TABLE Route DROP CONSTRAINT IF EXISTS FK_Route_User_UpdatedBy;

IF OBJECT_ID('RouteTrip', 'U') IS NOT NULL
    ALTER TABLE RouteTrip DROP CONSTRAINT IF EXISTS FK_RouteTrip_Route;
IF OBJECT_ID('RouteTrip', 'U') IS NOT NULL
    ALTER TABLE RouteTrip DROP CONSTRAINT IF EXISTS FK_RouteTrip_CreatedBy;
IF OBJECT_ID('RouteTrip', 'U') IS NOT NULL
    ALTER TABLE RouteTrip DROP CONSTRAINT IF EXISTS FK_RouteTrip_UpdatedBy;

IF OBJECT_ID('Town', 'U') IS NOT NULL
    ALTER TABLE Town DROP CONSTRAINT IF EXISTS FK_Town_Region;

IF OBJECT_ID('Region', 'U') IS NOT NULL
    ALTER TABLE Region DROP CONSTRAINT IF EXISTS FK_Region_Country;

IF OBJECT_ID('[User]', 'U') IS NOT NULL
    ALTER TABLE [User] DROP CONSTRAINT IF EXISTS FK_User_UserRole;

IF OBJECT_ID('OperatorContact', 'U') IS NOT NULL
    ALTER TABLE OperatorContact DROP CONSTRAINT IF EXISTS FK_OperatorContact_Operator;
IF OBJECT_ID('OperatorContact', 'U') IS NOT NULL
    ALTER TABLE OperatorContact DROP CONSTRAINT IF EXISTS FK_OperatorContact_Person;

IF OBJECT_ID('Ticket', 'U') IS NOT NULL
    ALTER TABLE Ticket DROP CONSTRAINT IF EXISTS FK_Ticket_RouteId;
IF OBJECT_ID('Ticket', 'U') IS NOT NULL
    ALTER TABLE Ticket DROP CONSTRAINT IF EXISTS FK_Ticket_UserId;

-- Now drop tables
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS RouteTrip;
DROP TABLE IF EXISTS OperatorContact;
DROP TABLE IF EXISTS Route;
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS Operator;
DROP TABLE IF EXISTS OperatorType;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS LocationType;
DROP TABLE IF EXISTS Town;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS UserRole;



---COMMIT