SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRoleDuty](
	[UserRoleDutyId] [int] IDENTITY(1,1) NOT NULL,
    [UserId] [int] NOT NULL,
    [UserRoleId] [int] NOT NULL,
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserRoleDuty] ADD PRIMARY KEY CLUSTERED 
(
	[UserRoleDutyId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
