name: Factory workflow

on: 
  workflow_dispatch:
  push:
     branches: ['main']
 
jobs:
    build: 
        runs-on: ubuntu-latest

        steps: 
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
                dotnet-version: 8.0.x

        - name: Restore Dependencies
          run: dotnet restore

        - id: build
          name:  Build
          run: dotnet build --no-restore

        #- id: test
          #if: steps.build.outcome == 'success'
          #name: Test
          #run: dotnet test "TestTheFactory.csproj" --collect "XPlat Code Coverate"

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: dotnet-webapp

        - name: Azure Login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy To Azure
          uses: azure/webapps-deploy@v2
          with:
            app-name:           
            package:      
