name: Factory workflow

on: 
  workflow_dispatch:
  push:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - id: build
      name: Build
      run: dotnet build ./TheFactory/TheFactory.csproj --no-restore

    # Uncomment if you want to run tests
    # - id: test
    #   if: steps.build.outcome == 'success'
    #   name: Test
    #   run: dotnet test "TestTheFactory.csproj" --collect "XPlat Code Coverage"

    - id: publish
      name: Publish
      run: dotnet publish ./TheFactory/TheFactory.csproj -c Release -r linux-x64 --self-contained false -o ./publish

    - name: List published files
      run: ls -lh ./publish

    - name: Upload Published Files
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapp
        path: publish/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-webapp
        path: ./publish

    - name: Zip for Azure
      run: |
        cd publish
        zip -r ../TheFactory.zip ./*

    - name: Inspect ZIP (debug)
      run: unzip -l TheFactory.zip

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.FACTORY_AUTH_SECRET }}

    - name: Deploy To Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: AzureLinuxAppService
        package: TheFactory.zip
