name: Azure .NET Deploy Workflow

on: 
  workflow_dispatch:
  push:
    branches: ['main', 'dev']

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./TheFactory/TheFactory.csproj

    - name: Build
      run: dotnet build ./TheFactory/TheFactory.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./TheFactory/TheFactory.csproj --configuration Release --output ./publish

    - name: Zip published app
      run: |
        cd publish
        zip -r ../TheFactory.zip .
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapp
        path: ./TheFactory.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-webapp
        path: ./

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.FACTORY_AUTH_SECRET }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: AzureLinuxAppService
        package: ./TheFactory.zip